### PR TITLE
feat(dex): added serebii link

### PR DESCRIPTION
**Pull request by ashcoding**
Fixes https://github.com/robinjoseph08/pokedextracker.com/issues/138 together with https://github.com/robinjoseph08/pokedextracker.com/pull/137.

This provides ```serebii_url```.

### CODE REVIEW

**Comment by ashcoding** [comment]
I also had to edit some of the other files with missing ```;``` that was reported back when running ```npm run lint```.

This was causing Travis to fail.

**Comment by robinjoseph08** [comment]
Thanks for taking the time to do this! Sorry about the linting error, that's my fault. I should've been shrinkwrapping the dev dependencies as well as the normal dependencies. I've fixed that in `master`, so if you rebase off of upstream, your commit will be clean and dedicated to the Serebii change.

To make sure the correct version of `left-pad` gets saved, you'll need to run `npm shrinkwrap --dev` as well. After you've rebased, go ahead and run the following to ensure your `node_modules` are correct (which is necessary for you to shrinkwrap):

- `npm i` - this will get your `node_modules` correct with the `npm-shrinkwrap.json`
- `npm i left-pad -S` - this will install `left-pad` again since the `npm i` will remove it
- `npm shrinkwrap --dev` - this will make a new `npm-shrinkwrap.json` so that everyone subsequently will get the exact version of `left-pad` you installed

After doing that and squashing your commits, this PR will be ready to merged!

**Comment by ashcoding** [comment]
No problem! I'm just scratching my own itch. 

Did all that is mentioned in your comment. Just a note, there seems to be 3 other modules updated in ```npm-shrinkwrap.json``` after running ```npm shrinkwrap --dev```.

Besides that, all good to go.

**Comment by robinjoseph08** [comment]
No worries, it doesn't look like actual modules were updated (version numbers changed). The shrinkwrap just readjusted some `from` and `resolved` properties, which it does every now and then. No harm done. 

LGTM! I'll let you know when it's been deployed so you can confirm the front-end changes. And once that's been finished, well tackle the design stuff.

**Pull request merged**
